spring:
  application:
    name: inf-sys-server

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  upload:
    server-url: 'https://cs.vsu.ru/is'
    base-files-folder: ${BASE_FILES_FOLDER}
  security:
    jwt:
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
    ldap:
      enabled: ${LDAP_ENABLED:true}
      host: csfs.cs.vsu.ru
      port: 389
      email-host: cs.vsu.ru
  services:
    parser:
      base-url: ${PARSER_URL}
      # base-url: 'https://cs.vsu.ru/is/inf-sys-parser/'
