spring:

  datasource:
    url: jdbc:postgresql://localhost:5433/inf-sys
    username: inf-sys-server
    password: ${POSTGRES_PASSWORD}
  liquibase:
    contexts: local
    enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

server:
  port: ${SERVER_PORT}

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  upload:
    server-url: 'http://localhost:${SERVER_PORT}'
    base-files-folder: ${BASE_FILES_FOLDER}