spring:
  application:
    name: inf-sys-server

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql

application:
  upload:
    server-url: 'http://cs.vsu.ru:80/is/api/'
    base-files-folder: 'files/'
  security:
    jwt:
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
    ldap:
      host: csfs.cs.vsu.ru
      port: 389
      email-host: cs.vsu.ru
