spring:

  datasource:
    url: jdbc:postgresql://localhost:5433/inf-sys
    username: inf-sys-server
    password: ${POSTGRES_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 3030