spring:

  datasource:
    url: jdbc:postgresql://postgresql:5432/inf-sys-server
    username: inf-sys-server
    password: ${POSTGRES_PASSWORD}
  liquibase:
    contexts: local
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}