CREATE TABLE students
(
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id    BIGINT NOT NULL,
    patronymic VARCHAR(100),
    course     INT,
    group_nm   VARCHAR(50),
    start_year INT,
    end_year   INT,
    supervisor BIGINT,
    image_url  text,

    FOREIGN KEY (user_id) REFERENCES users (id),
    FOREIGN KEY (supervisor) REFERENCES employees (id)
);
