--liquibase formatted sql

--changeset codex:202603301200

CREATE TABLE student_topic_assignments
(
    id                     BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    student_login          VARCHAR(255) NOT NULL UNIQUE,
    student_full_name      VARCHAR(255) NOT NULL,
    course_work_topic      TEXT,
    thesis_topic           TEXT,
    supervisor_login       VARCHAR(255) NOT NULL,
    supervisor_full_name   VARCHAR(255) NOT NULL,
    supervisor_employee_id BIGINT,
    imported_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_student_topic_assignments_supervisor_employee
        FOREIGN KEY (supervisor_employee_id) REFERENCES employees (id)
);
