--liquibase formatted sql

--changeset codex:202605141400

CREATE TABLE student_nir_records
(
    id                     BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    student_id             BIGINT,
    student_login          VARCHAR(255) NOT NULL,
    student_full_name      VARCHAR(255) NOT NULL,
    supervisor_employee_id BIGINT,
    supervisor_full_name   VARCHAR(255),
    thesis_topic           TEXT,
    nir7_grade             VARCHAR(64),
    nir7_docs              VARCHAR(255),
    predefense1_grade      VARCHAR(64),
    predefense2_grade      VARCHAR(64),
    nir8_grade             VARCHAR(64),
    nir8_docs              VARCHAR(255),
    is_debtor              BOOLEAN      NOT NULL DEFAULT FALSE,
    imported_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_student_nir_records_student
        FOREIGN KEY (student_id) REFERENCES students (id),
    CONSTRAINT fk_student_nir_records_supervisor_employee
        FOREIGN KEY (supervisor_employee_id) REFERENCES employees (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uniq_student_nir_records_student_id
    ON student_nir_records (student_id)
    WHERE student_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_student_nir_records_student_login
    ON student_nir_records (student_login);
