--liquibase formatted sql

--changeset nagorniy:202604091200_tab_content

CREATE TABLE tab_content (
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tab_id     BIGINT NOT NULL UNIQUE,
    content    TEXT NOT NULL DEFAULT '',
    CONSTRAINT fk_tab_content_tab
        FOREIGN KEY (tab_id) REFERENCES navigation_tabs(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX idx_tab_content_tab_id ON tab_content(tab_id);