--liquibase formatted sql

--changeset antonkiselev:202604061200
CREATE TABLE department
(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL UNIQUE,
    description TEXT
)