name: Redeploy Image on Host

on:
  workflow_dispatch:

jobs:
  redeploy:
    runs-on: self-hosted

    steps:
      - name: Redeploy containers
        shell: bash
        run: |
          set -e
          cd /dev-server
          docker compose pull
          docker compose up -d
          docker ps